"""empty message

Revision ID: 013fd347714c
Revises: 4d81ef2aea00
Create Date: 2021-04-27 13:36:17.893249

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '013fd347714c'
down_revision = '4d81ef2aea00'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('firstname', sa.String(length=50), nullable=True))
    op.add_column('post', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.add_column('post', sa.Column('lastname', sa.String(length=80), nullable=True))
    op.create_index(op.f('ix_post_last_seen'), 'post', ['last_seen'], unique=False)
    op.drop_index('ix_profile_last_seen', table_name='profile')
    op.drop_column('profile', 'last_seen')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('last_seen', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.create_index('ix_profile_last_seen', 'profile', ['last_seen'], unique=False)
    op.drop_index(op.f('ix_post_last_seen'), table_name='post')
    op.drop_column('post', 'lastname')
    op.drop_column('post', 'last_seen')
    op.drop_column('post', 'firstname')
    # ### end Alembic commands ###
