"""add post is_deleted

Revision ID: 1a005ec82d0f
Revises: 6931c783ab3a
Create Date: 2021-04-15 15:21:42.879451

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1a005ec82d0f'
down_revision = '6931c783ab3a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'is_deleted')
    # ### end Alembic commands ###
