"""some changes

Revision ID: 4f5537405ead
Revises: 09a7f2a6688b
Create Date: 2021-04-15 14:17:33.925091

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f5537405ead'
down_revision = '09a7f2a6688b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('media_user_id_fkey', 'media', type_='foreignkey')
    op.drop_column('media', 'user_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media', sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('media_user_id_fkey', 'media', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###
