"""add post media

Revision ID: 6931c783ab3a
Revises: 4f5537405ead
Create Date: 2021-04-15 15:04:23.687718

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6931c783ab3a'
down_revision = '4f5537405ead'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('photo_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'post', 'media', ['photo_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'post', type_='foreignkey')
    op.drop_column('post', 'photo_id')
    # ### end Alembic commands ###
