"""new column in profile

Revision ID: 6d8c73624f3d
Revises: 54c2e7de3926
Create Date: 2021-04-11 19:43:06.945184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6d8c73624f3d'
down_revision = '54c2e7de3926'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_profile_last_seen'), 'profile', ['last_seen'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_profile_last_seen'), table_name='profile')
    op.drop_column('profile', 'last_seen')
    # ### end Alembic commands ###
