"""empty message

Revision ID: 82410f3ca206
Revises: 013fd347714c
Create Date: 2021-04-27 13:49:10.727454

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '82410f3ca206'
down_revision = '013fd347714c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_post_last_seen', table_name='post')
    op.drop_column('post', 'lastname')
    op.drop_column('post', 'firstname')
    op.drop_column('post', 'last_seen')
    op.add_column('user', sa.Column('firstname', sa.String(length=50), nullable=True))
    op.add_column('user', sa.Column('last_seen', sa.DateTime(), nullable=True))
    op.add_column('user', sa.Column('lastname', sa.String(length=80), nullable=True))
    op.create_index(op.f('ix_user_last_seen'), 'user', ['last_seen'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_last_seen'), table_name='user')
    op.drop_column('user', 'lastname')
    op.drop_column('user', 'last_seen')
    op.drop_column('user', 'firstname')
    op.add_column('post', sa.Column('last_seen', postgresql.TIMESTAMP(), autoincrement=False, nullable=True))
    op.add_column('post', sa.Column('firstname', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    op.add_column('post', sa.Column('lastname', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
    op.create_index('ix_post_last_seen', 'post', ['last_seen'], unique=False)
    # ### end Alembic commands ###
