"""edit

Revision ID: 9032b586ceda
Revises: 316f4a0f394a
Create Date: 2021-04-13 18:10:20.172114

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9032b586ceda'
down_revision = '316f4a0f394a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('profile_photo_id_fkey', 'profile', type_='foreignkey')
    op.drop_column('profile', 'photo_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('profile', sa.Column('photo_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('profile_photo_id_fkey', 'profile', 'media', ['photo_id'], ['id'])
    # ### end Alembic commands ###
