"""followers table

Revision ID: e6a340453047
Revises: 1a005ec82d0f
Create Date: 2021-04-19 14:06:21.412209

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e6a340453047'
down_revision = '1a005ec82d0f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    op.drop_table('user_media')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_media',
    sa.Column('user_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('media_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['media_id'], ['media.id'], name='user_media_media_id_fkey'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='user_media_user_id_fkey')
    )
    op.drop_table('followers')
    # ### end Alembic commands ###
